### ISSUE TITLE
Missing dependency to BadgeBundle

### ISSUE THREAD

**Issue by Elorfin** [iCAPLyon1/PortfolioBundle#42]
Hi,
There is a dependency to the BadgeBundle in the Model. When you want to execute operation to DB, it throws the following error : 

```
[Doctrine\ORM\Mapping\MappingException]                                                                
The target-entity Icap\BadgeBundle\Entity\Badge cannot be found in 'Icap\PortfolioBundle\Entity\Widget\BadgesWidgetBadge#badge'. 
```

I'm not sure the dependency is wanted, so I open an issue instead of creating a pull request to update composer.json.

**Comment by maxailloud** [comment]
I tagged a new version a few hours ago.
Try the new tag.

I screwed up merging in a branch an other I shouldn't.
My bad.
